# Generated by Django 2.1.5 on 2020-04-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products", old_name="selling_price", new_name="mrp",
        ),
    ]
