# Generated by Django 2.2.9 on 2020-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="shift_time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="shift_time_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
