# Generated by Django 2.2.9 on 2020-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_bill_items_product_transaction_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "M"), ("F", "F"), ("Other", "Other")],
                max_length=15,
                null=True,
            ),
        ),
    ]
